$ANSIBLE_VAULT;1.1;AES256
38353662326334633033646663623663663237353663393631353565363665333337643364623664
3965656261623530633737613731666633636436636661380a653839656231383032623963393062
61343164653138646466383363646138316337646338393165656562396366663538353337396435
6666633532306432390a313130653131386430663539363037373131353364343431656131653163
63373364313132303830333133663463333064343033323433303532653666373330363635383538
34666431383363323433616134363938613631343966633032326139353632356664376162346664
38353835653836373331656536633633363861343266363538303834613465356636326632363462
32383832316166653231356566393131643339336461663062396636616130333464623735653463
38373064383462643761613235386434656231376262633639393361653663643364613639653135
34303239653039363838386337393739653263646265666362663234313433376131643262656466
37393362393737373338306365636334313735313731636337386638666265346236356437343830
64323565643266613938323866356536616338393034396430333561363434613836636562363432
34633135346238383438356336663733316265393938376236646264643063346262353562646565
30613837666530646238613236383166613166346234613237303739356637393063383435323131
37666566323036643630626233653965663234666435633063663265623133613238383031333832
37326664323033653966366565616530623032343131363837393562616239643231653133313732
30646234353861623838643135333334326639356134353036316638643762633365393235663231
38623563633933393032306661353037646330373430633832646133353533613035306534306163
64343536323436376666316430613663323134326634343461333934386137373933326239383636
32396131346665323665616564343339626232666331316465393461376263363832316233356432
34333463663866626464346635363432636538313336623433343366303464383633316364353831
3335613731623536393164363731633835323635316437653436
